name: task_manager
description: A Flutter application for managing tasks with local persistence.
version: 1.0.0+1

environment:
  sdk: '^3.9.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true